### ISSUE TITLE
Email alert for approval of new user

### ISSUE THREAD

**Issue by PaulLintott** [Indicia-Team/ecobat#14]
Just wondering if we could add an email alert so that if someone registers we can an automated email to let us know so we can log on for approval. 

Alternatively I would be happy to allow people to register without being approved as long as you think the spam prevention modules were good enough? What do the Consultants Portal do? I would rather registering was a speedy process rather than having to wait for us to approve if we are out of office which could turn people away from using Ecobat.

**Comment by johnvanbreda** [comment]
This has now been done - just to confirm though:

Most of the sites I work on (including the Consultants Portal) will allow people to self-register, relying on email confirmation plus spam prevention to prevent spammers. This solution prevents the majority of spam registrations but not all - some will always get through. However as the site is currently set up I think a logged in user will only gain access to upload a CSV file (far too complex for a spammer to work out) or generate outputs using the manual analysis. Even if a spambot manages to fill in the form, the output won't be of any value in the spam world.
