### ISSUE TITLE
Stratification by pass definition

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/ecobat#4]
For the pass definition, my feeling is that you simply cannot compare data captured using a different definition of the pass, not unless someone first studies a controlled dataset which captured data using multiple definitions simultaneously so we could get an idea of how they can be compared (if at all). Assuming we don’t have this information, I think we should consider the reference dataset as effectively being subdivided into several subsets and you can only compare against one at a time. Therefore when you manually input the parameters to run a comparison against you must be forced to enter a pass definition along with the number of passes and your reference output will only be compared against this definition’s dataset. It’s unfortunate that we have to subdivide the dataset in this way but I think it’s the scientifically honest approach. If you import data, then I can’t see any big reason not to allow variation in the pass definitions between rows in the spreadsheet. But, if you then try to run an analysis using an import that covers multiple pass definitions you should be told that this can’t be done.

**Comment by johnvanbreda** [comment]
Response from Paul:
Agree with this, previously I was thinking that whilst we have it listed as ‘essential’ (i.e. flagging up its importance) we would leave it to the individual user to decide if they wanted to stratify by it. However, I agree that taking a stand for best practice is a really good idea from the start and so stratifying automatically by pass definition is the way forward. I think we could also work with CIEEM in getting an established, standardised pass definition used across the industry, and using Ecobat would be a great way to demonstrate how much more productively data could be used if everyone kept to the same methodology. The only situation to be aware of would be when someone uploaded a dataset with multiple pass definitions (which is highly unlikely to occur) but then got an error in the output – could we have a pop up explaining why this occurred or would we be able to deal with a situation where we gave outputs for different pass definitions.. i.e. you had moderate activity for p.pip where passes were defined as 1 second intervals… you had high activity for Myotis where passes were defined as registration..

**Comment by johnvanbreda** [comment]
So, we have 2 possibilities:
1) If you try to run an analysis using an import that contains more than one pass definition, the analysis is rejected and you are told why.
2) You are allowed to run an analysis using an import with multiple pass definitions. However for the purposes of the output each pass definition is handled separately - you effectively get multiple outputs, one per pass definition. 

As this will be a rare circumstance anyway, option 1) has the additional benefit of promoting adoption of a single standard definition, so that would be my preferred choice if you agree.

**Comment by PaulLintott** [comment]
I'm happy to go for 1)

**Comment by johnvanbreda** [comment]
Good, that's how it works now ;)
