### ISSUE TITLE
Stratification by detector make and/or model

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/ecobat#5]
With reference to #4, for the detector make (and model?) my gut feeling is that it is not quite so clear cut. You might well want to run an analysis which includes the dataset for all different detectors, since I would hope that having a different detector does not fundamentally change the number of passes you recorded (assuming that the detector works reasonably well of course). So I would suggest that for the detector we are less draconian and we allow comparison across different detectors but also provide the option to limit the dataset to a single manufacturer much like we do with date ranges, geographic areas etc. Where I am less clear is the relationship between make and model – remember that model is a free text field so we might be prone to spelling mistakes and different ways of writing the model if you try to limit to one model. But, if you try to limit to a single manufacturer, then aren’t there going to be bigger differences between the models of one manufacturer than between manufacturers in some cases?

**Comment by johnvanbreda** [comment]
Response from Paul:
Agree with this, fundamentally there will be differences between detectors but this is relatively marginal in the grand scheme of things (But some consultants do feel passionate about this so having the ability to select if you wish to stratify works well here). It is based more on intuition than science but I would be fairly confident that there is more variance between makes than between models and so ‘make’ is much more important. For example, most of the upgrades by Wildlife Acoustics between SM2’s and SM4’s (one of the commonest detectors used by consultants) is on battery life, gps capacity etc rather than significant changes in detection capability. So, my thinking was that we’d be collecting ‘model’ as a free text field for future use, so potentially down the line it could be offered as an option for stratification if we had the database size to accommodate this (I’m thinking years rather than months here in terms of when it would happen). I’ll get in contact with colleagues who know a lot more about the intricacies of detectors and get their thoughts on the make versus model comparison (But given everyone is on summer holiday/bank holiday I probably won’t get replies until the middle of next week at the earliest).

**Comment by johnvanbreda** [comment]
Ok, leaving this on hold for now. The proposal (TBC) is to allow selection of the detector manufacturer as one of the parameters to use when defining the reference set.

**Comment by PaulLintott** [comment]
So, I've heard from a few people and Make seems a lot more important than Model so happy to go with that as the option that is available to stratify by.

**Comment by johnvanbreda** [comment]
This should now work.
