### ISSUE TITLE
Going live...

### ISSUE THREAD

**Issue by PaulLintott** [Indicia-Team/ecobat#9]
I thought I could use this post to highlight/and tick off the things that we need to do before going live. If possible I would like to go for a soft launch next week so collaborators etc can see the new site. 

We're reaching a crucial time with the new Bats and Wind Turbines guidance and the use of Ecobat is highlighted as best practice in it, however stakeholders want to see it working before approving its inclusion within the guidance.

As far as I'm aware, we need to do the following:
- Finish off information pages about Ecobat (PRL & SD)
- Ensure there aren't errors cropping up when performing data analysis (PRL & SD to note when these errors occur, and JVB to problem solve).

John - do you have any more critical updates or changes which need completing other than fixing any glitches that we discover?

**Comment by johnvanbreda** [comment]
I think that the main areas of discussion are currently around the analysis itself. This can easily be tweaked and revised when live so I don't have any big issues with this. The main thing I need to do is move the code and configuration onto the live server, so I just need a bit of notice to plan this in.
